const mockData =  [
    { image: 'images/pic.jpg', name: 'Madusha' },
    { image: 'images/display-pictures/face1.jpg', name: 'Lukey' },
    { image: 'images/display-pictures/face2.jpg', name: 'Alex' },
    { image: 'images/display-pictures/face3.jpg', name: 'Vic' },
    { image: 'images/display-pictures/face4.jpg', name: 'Remi' },
    { image: 'images/display-pictures/face5.png', name: 'Jean' },
    { image: 'images/display-pictures/face1.jpg', name: 'Charlie' },
    { image: 'images/display-pictures/face2.jpg', name: 'Zephyr' },
    { image: 'images/display-pictures/face3.png', name: 'Ray' },
    { image: 'images/display-pictures/face4.jpg', name: 'Sam' },
    { image: 'images/display-pictures/face5.jpg', name: 'Cory' },
    { image: 'images/display-pictures/face1.jpg', name: 'Jordan' },
    { image: 'images/display-pictures/face2.png', name: 'Amila' },
    { image: 'images/display-pictures/face3.jpg', name: 'Max' },
    { image: 'images/display-pictures/face4.jpg', name: 'Ashley' },
    { image: 'images/display-pictures/face5.jpg', name: 'Angel' },
    { image: 'images/display-pictures/face1.jpg', name: 'Jessie' },
    { image: 'images/display-pictures/face2.jpg', name: 'Lou' },
]